{{- if .Values.global.serviceAccountName -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceAccountName }}
  labels:
    {{- include "exploit-iq-models.labels" . | nindent 4 }}
{{- end }}
